#!/bin/bash

# Project variables
projectName="Baton"
version="1.0.0 Genesis"

# Function to compile the Java source files
compile() {
  echo "Compiling Java source files... $projectName project"
  rm -rf ./bin
  mkdir ./bin
  # Find all Java files in src and compile them
  find ./src -name "*.java" -print | xargs javac -d ./bin
  echo "Compilation completed."
}

# Function to run the main class 'Baton'
run() {
  echo "Running the main class '$projectName'..."
  echo " "
  echo " "
  echo " "
  java -cp ./bin src.$projectName
}

help() {
  echo "Usage: ./baton [option]"
  echo "Options:"
  echo "  --compile | -c : Compile the Java source files"
  echo "  --run | -r : Run the main class '$projectName'"
  echo "  --compile-run | -cr : Compile and run the main class '$projectName'"
}

showVersion() {
  echo "Version: $version"
}

# Check the passed argument
case $1 in
  --compile | -c)
    compile
    ;;
  --run | -r)
    run
    ;;
  --compile-run | -cr)
    compile
    run
    ;;
  --help | -h)
    help
    ;;
  --version | -v)
    showVersion
    ;;
  *)
    echo "Invalid option."
    help
    ;;
esac